### ISSUE TITLE
Add device type to description?

### ISSUE THREAD

**Issue by flatsiedatsie** [tim-hellhake/medisana-ks250-adapter#1]
It's not clear from the description on the adapter overview page what a 'KS-250' is. Could you expand the description to explain a bit what it is? As a user I might be tempted to buy that device if I see there is support for it.

Ah, it's a kitchen scale :-D

**Comment by flatsiedatsie** [comment]
Not a good idea?

**Comment by tim-hellhake** [comment]
I added `kitchen scale` to the Readme and the description.
I thought that would be sufficient 😄
What should I add?

**Comment by flatsiedatsie** [comment]
I was hoping for the word kitchen scale in the JSON, so that it appears in the "add new add-on" list. For now that seems like the best place to find out which devices the WebThings Gateway supports.

**Comment by tim-hellhake** [comment]
Like this? 😬
https://github.com/mozilla-iot/addon-list/pull/283/files

**Comment by flatsiedatsie** [comment]
Perfect!
